version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zakariaeelhajri/my_django_app:v2
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_drf:/app/todo_drf
    ports:
      - "8000:8000"

