# Generated by Django 4.1.4 on 2023-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='competed',
            new_name='completed',
        ),
    ]
